services:
  multipassport:
    build:
      context: ./
    container_name: multipassport
    ports:
      - "12345:1337"
    environment:
      - ${FLAG}:${FLAG}
    networks: 
      multipassport:

networks:
  multipassport:
    driver: bridge